global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'vllm-mock-server'
    static_configs:
      - targets: ['vllm-mock-server:8000']

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
